### ISSUE TITLE
"ld: library not found for -llablgl" when I dune build

### ISSUE THREAD

**Issue by anentropic** [garrigue/lablgl#4]
I originally asked over here https://github.com/sanette/oplot/issues/5

but I guess the real issue is something wrong with my lablgl install

I am trying to use `oplot`, which has `lablgl` as a dependency.

oplot works fine in ocaml shell (with `#use "topfind"` if that is relevant), suggesting that lablgl is installed ok.

But when I add `(libraries oplot)` to the dune file of my project, when I `dune build` I get:

```
ld: library not found for -llablgl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
File "_none_", line 1:
Error: Error while building custom runtime system
```

I have:
```
$ opam list | grep gl
lablgl                1.06        Interface to OpenGL
```

Any ideas how I could get this working?

(I am guessing I may need to add something to my `LD_LIBRARY_PATH` but I'm not sure what)

**Comment by anentropic** [comment]
Well, I eventually found what is causing this

I gradually copied files from my failing project into a new empty project until the error reproduced

no error, until I copied the `tests/` dir, whose dune file looks like:
```
(tests
 (names test_myproject)
 (modes byte exe)
 (preprocess
  (pps ppx_deriving.show ppx_deriving_popper))
 (libraries popper gg myproject))
```

experimenting further it seems the problem is due to `(modes byte)`, which I'd added for sake of using `ocamldebug`

if I omit the `modes` stanza or have `(modes exe)` then it builds successfully

**Comment by garrigue** [comment]
Great you could solve this yourself !
